// Code generated by protoc-gen-go. DO NOT EDIT.
// source: premierleague.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TableRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableRequest) Reset()         { *m = TableRequest{} }
func (m *TableRequest) String() string { return proto.CompactTextString(m) }
func (*TableRequest) ProtoMessage()    {}
func (*TableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{0}
}

func (m *TableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableRequest.Unmarshal(m, b)
}
func (m *TableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableRequest.Marshal(b, m, deterministic)
}
func (m *TableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableRequest.Merge(m, src)
}
func (m *TableRequest) XXX_Size() int {
	return xxx_messageInfo_TableRequest.Size(m)
}
func (m *TableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TableRequest proto.InternalMessageInfo

func (m *TableRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type Table struct {
	TeamName             string   `protobuf:"bytes,1,opt,name=teamName,proto3" json:"teamName,omitempty"`
	TeamPlayed           int32    `protobuf:"varint,2,opt,name=teamPlayed,proto3" json:"teamPlayed,omitempty"`
	TeamWon              int32    `protobuf:"varint,3,opt,name=teamWon,proto3" json:"teamWon,omitempty"`
	TeamDrawn            int32    `protobuf:"varint,4,opt,name=teamDrawn,proto3" json:"teamDrawn,omitempty"`
	TeamLost             int32    `protobuf:"varint,5,opt,name=teamLost,proto3" json:"teamLost,omitempty"`
	TeamGF               int32    `protobuf:"varint,6,opt,name=teamGF,proto3" json:"teamGF,omitempty"`
	TeamGA               int32    `protobuf:"varint,7,opt,name=teamGA,proto3" json:"teamGA,omitempty"`
	TeamGD               int32    `protobuf:"varint,8,opt,name=teamGD,proto3" json:"teamGD,omitempty"`
	TeamPoints           int32    `protobuf:"varint,9,opt,name=teamPoints,proto3" json:"teamPoints,omitempty"`
	TeamCapital          int32    `protobuf:"varint,10,opt,name=teamCapital,proto3" json:"teamCapital,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{1}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

func (m *Table) GetTeamPlayed() int32 {
	if m != nil {
		return m.TeamPlayed
	}
	return 0
}

func (m *Table) GetTeamWon() int32 {
	if m != nil {
		return m.TeamWon
	}
	return 0
}

func (m *Table) GetTeamDrawn() int32 {
	if m != nil {
		return m.TeamDrawn
	}
	return 0
}

func (m *Table) GetTeamLost() int32 {
	if m != nil {
		return m.TeamLost
	}
	return 0
}

func (m *Table) GetTeamGF() int32 {
	if m != nil {
		return m.TeamGF
	}
	return 0
}

func (m *Table) GetTeamGA() int32 {
	if m != nil {
		return m.TeamGA
	}
	return 0
}

func (m *Table) GetTeamGD() int32 {
	if m != nil {
		return m.TeamGD
	}
	return 0
}

func (m *Table) GetTeamPoints() int32 {
	if m != nil {
		return m.TeamPoints
	}
	return 0
}

func (m *Table) GetTeamCapital() int32 {
	if m != nil {
		return m.TeamCapital
	}
	return 0
}

type TableReply struct {
	Teams                []*Table `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableReply) Reset()         { *m = TableReply{} }
func (m *TableReply) String() string { return proto.CompactTextString(m) }
func (*TableReply) ProtoMessage()    {}
func (*TableReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{2}
}

func (m *TableReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableReply.Unmarshal(m, b)
}
func (m *TableReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableReply.Marshal(b, m, deterministic)
}
func (m *TableReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableReply.Merge(m, src)
}
func (m *TableReply) XXX_Size() int {
	return xxx_messageInfo_TableReply.Size(m)
}
func (m *TableReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TableReply.DiscardUnknown(m)
}

var xxx_messageInfo_TableReply proto.InternalMessageInfo

func (m *TableReply) GetTeams() []*Table {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *TableReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type TeamRequest struct {
	TeamName             string   `protobuf:"bytes,1,opt,name=teamName,proto3" json:"teamName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamRequest) Reset()         { *m = TeamRequest{} }
func (m *TeamRequest) String() string { return proto.CompactTextString(m) }
func (*TeamRequest) ProtoMessage()    {}
func (*TeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{3}
}

func (m *TeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamRequest.Unmarshal(m, b)
}
func (m *TeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamRequest.Marshal(b, m, deterministic)
}
func (m *TeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamRequest.Merge(m, src)
}
func (m *TeamRequest) XXX_Size() int {
	return xxx_messageInfo_TeamRequest.Size(m)
}
func (m *TeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamRequest proto.InternalMessageInfo

func (m *TeamRequest) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

type Player struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Team                 string   `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Nationality          string   `protobuf:"bytes,3,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Position             string   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Appearences          int32    `protobuf:"varint,5,opt,name=appearences,proto3" json:"appearences,omitempty"`
	Goals                int32    `protobuf:"varint,6,opt,name=goals,proto3" json:"goals,omitempty"`
	Assists              int32    `protobuf:"varint,7,opt,name=assists,proto3" json:"assists,omitempty"`
	Passes               int32    `protobuf:"varint,8,opt,name=passes,proto3" json:"passes,omitempty"`
	Interceptions        int32    `protobuf:"varint,9,opt,name=interceptions,proto3" json:"interceptions,omitempty"`
	Tackles              int32    `protobuf:"varint,10,opt,name=tackles,proto3" json:"tackles,omitempty"`
	Fouls                int32    `protobuf:"varint,11,opt,name=fouls,proto3" json:"fouls,omitempty"`
	Price                int32    `protobuf:"varint,12,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{4}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *Player) GetNationality() string {
	if m != nil {
		return m.Nationality
	}
	return ""
}

func (m *Player) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Player) GetAppearences() int32 {
	if m != nil {
		return m.Appearences
	}
	return 0
}

func (m *Player) GetGoals() int32 {
	if m != nil {
		return m.Goals
	}
	return 0
}

func (m *Player) GetAssists() int32 {
	if m != nil {
		return m.Assists
	}
	return 0
}

func (m *Player) GetPasses() int32 {
	if m != nil {
		return m.Passes
	}
	return 0
}

func (m *Player) GetInterceptions() int32 {
	if m != nil {
		return m.Interceptions
	}
	return 0
}

func (m *Player) GetTackles() int32 {
	if m != nil {
		return m.Tackles
	}
	return 0
}

func (m *Player) GetFouls() int32 {
	if m != nil {
		return m.Fouls
	}
	return 0
}

func (m *Player) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type TeamReply struct {
	Players              []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Err                  string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TeamReply) Reset()         { *m = TeamReply{} }
func (m *TeamReply) String() string { return proto.CompactTextString(m) }
func (*TeamReply) ProtoMessage()    {}
func (*TeamReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{5}
}

func (m *TeamReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamReply.Unmarshal(m, b)
}
func (m *TeamReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamReply.Marshal(b, m, deterministic)
}
func (m *TeamReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamReply.Merge(m, src)
}
func (m *TeamReply) XXX_Size() int {
	return xxx_messageInfo_TeamReply.Size(m)
}
func (m *TeamReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamReply.DiscardUnknown(m)
}

var xxx_messageInfo_TeamReply proto.InternalMessageInfo

func (m *TeamReply) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *TeamReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type PositionRequest struct {
	Position             string   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionRequest) Reset()         { *m = PositionRequest{} }
func (m *PositionRequest) String() string { return proto.CompactTextString(m) }
func (*PositionRequest) ProtoMessage()    {}
func (*PositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{6}
}

func (m *PositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionRequest.Unmarshal(m, b)
}
func (m *PositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionRequest.Marshal(b, m, deterministic)
}
func (m *PositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionRequest.Merge(m, src)
}
func (m *PositionRequest) XXX_Size() int {
	return xxx_messageInfo_PositionRequest.Size(m)
}
func (m *PositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PositionRequest proto.InternalMessageInfo

func (m *PositionRequest) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type PositionReply struct {
	Players              []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Err                  string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PositionReply) Reset()         { *m = PositionReply{} }
func (m *PositionReply) String() string { return proto.CompactTextString(m) }
func (*PositionReply) ProtoMessage()    {}
func (*PositionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{7}
}

func (m *PositionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionReply.Unmarshal(m, b)
}
func (m *PositionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionReply.Marshal(b, m, deterministic)
}
func (m *PositionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionReply.Merge(m, src)
}
func (m *PositionReply) XXX_Size() int {
	return xxx_messageInfo_PositionReply.Size(m)
}
func (m *PositionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionReply.DiscardUnknown(m)
}

var xxx_messageInfo_PositionReply proto.InternalMessageInfo

func (m *PositionReply) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *PositionReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type CreatePlayerRequest struct {
	Name                 *Player  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlayerRequest) Reset()         { *m = CreatePlayerRequest{} }
func (m *CreatePlayerRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlayerRequest) ProtoMessage()    {}
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{8}
}

func (m *CreatePlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayerRequest.Unmarshal(m, b)
}
func (m *CreatePlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayerRequest.Marshal(b, m, deterministic)
}
func (m *CreatePlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayerRequest.Merge(m, src)
}
func (m *CreatePlayerRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlayerRequest.Size(m)
}
func (m *CreatePlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayerRequest proto.InternalMessageInfo

func (m *CreatePlayerRequest) GetName() *Player {
	if m != nil {
		return m.Name
	}
	return nil
}

type CreatePlayerReply struct {
	Ops                  string   `protobuf:"bytes,1,opt,name=ops,proto3" json:"ops,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlayerReply) Reset()         { *m = CreatePlayerReply{} }
func (m *CreatePlayerReply) String() string { return proto.CompactTextString(m) }
func (*CreatePlayerReply) ProtoMessage()    {}
func (*CreatePlayerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{9}
}

func (m *CreatePlayerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayerReply.Unmarshal(m, b)
}
func (m *CreatePlayerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayerReply.Marshal(b, m, deterministic)
}
func (m *CreatePlayerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayerReply.Merge(m, src)
}
func (m *CreatePlayerReply) XXX_Size() int {
	return xxx_messageInfo_CreatePlayerReply.Size(m)
}
func (m *CreatePlayerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayerReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayerReply proto.InternalMessageInfo

func (m *CreatePlayerReply) GetOps() string {
	if m != nil {
		return m.Ops
	}
	return ""
}

func (m *CreatePlayerReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DeletePlayerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Team                 string   `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlayerRequest) Reset()         { *m = DeletePlayerRequest{} }
func (m *DeletePlayerRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePlayerRequest) ProtoMessage()    {}
func (*DeletePlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{10}
}

func (m *DeletePlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlayerRequest.Unmarshal(m, b)
}
func (m *DeletePlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlayerRequest.Marshal(b, m, deterministic)
}
func (m *DeletePlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlayerRequest.Merge(m, src)
}
func (m *DeletePlayerRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePlayerRequest.Size(m)
}
func (m *DeletePlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlayerRequest proto.InternalMessageInfo

func (m *DeletePlayerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeletePlayerRequest) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

type DeletePlayerReply struct {
	Ops                  string   `protobuf:"bytes,1,opt,name=ops,proto3" json:"ops,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlayerReply) Reset()         { *m = DeletePlayerReply{} }
func (m *DeletePlayerReply) String() string { return proto.CompactTextString(m) }
func (*DeletePlayerReply) ProtoMessage()    {}
func (*DeletePlayerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{11}
}

func (m *DeletePlayerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlayerReply.Unmarshal(m, b)
}
func (m *DeletePlayerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlayerReply.Marshal(b, m, deterministic)
}
func (m *DeletePlayerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlayerReply.Merge(m, src)
}
func (m *DeletePlayerReply) XXX_Size() int {
	return xxx_messageInfo_DeletePlayerReply.Size(m)
}
func (m *DeletePlayerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlayerReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlayerReply proto.InternalMessageInfo

func (m *DeletePlayerReply) GetOps() string {
	if m != nil {
		return m.Ops
	}
	return ""
}

func (m *DeletePlayerReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type PlayerTransferRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Team                 string   `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerTransferRequest) Reset()         { *m = PlayerTransferRequest{} }
func (m *PlayerTransferRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerTransferRequest) ProtoMessage()    {}
func (*PlayerTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{12}
}

func (m *PlayerTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerTransferRequest.Unmarshal(m, b)
}
func (m *PlayerTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerTransferRequest.Marshal(b, m, deterministic)
}
func (m *PlayerTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerTransferRequest.Merge(m, src)
}
func (m *PlayerTransferRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerTransferRequest.Size(m)
}
func (m *PlayerTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerTransferRequest proto.InternalMessageInfo

func (m *PlayerTransferRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerTransferRequest) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

type PlayerTransferReply struct {
	Ops                  string   `protobuf:"bytes,1,opt,name=ops,proto3" json:"ops,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerTransferReply) Reset()         { *m = PlayerTransferReply{} }
func (m *PlayerTransferReply) String() string { return proto.CompactTextString(m) }
func (*PlayerTransferReply) ProtoMessage()    {}
func (*PlayerTransferReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4204cc63886395c8, []int{13}
}

func (m *PlayerTransferReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerTransferReply.Unmarshal(m, b)
}
func (m *PlayerTransferReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerTransferReply.Marshal(b, m, deterministic)
}
func (m *PlayerTransferReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerTransferReply.Merge(m, src)
}
func (m *PlayerTransferReply) XXX_Size() int {
	return xxx_messageInfo_PlayerTransferReply.Size(m)
}
func (m *PlayerTransferReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerTransferReply.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerTransferReply proto.InternalMessageInfo

func (m *PlayerTransferReply) GetOps() string {
	if m != nil {
		return m.Ops
	}
	return ""
}

func (m *PlayerTransferReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*TableRequest)(nil), "pb.TableRequest")
	proto.RegisterType((*Table)(nil), "pb.Table")
	proto.RegisterType((*TableReply)(nil), "pb.TableReply")
	proto.RegisterType((*TeamRequest)(nil), "pb.TeamRequest")
	proto.RegisterType((*Player)(nil), "pb.Player")
	proto.RegisterType((*TeamReply)(nil), "pb.TeamReply")
	proto.RegisterType((*PositionRequest)(nil), "pb.PositionRequest")
	proto.RegisterType((*PositionReply)(nil), "pb.PositionReply")
	proto.RegisterType((*CreatePlayerRequest)(nil), "pb.CreatePlayerRequest")
	proto.RegisterType((*CreatePlayerReply)(nil), "pb.CreatePlayerReply")
	proto.RegisterType((*DeletePlayerRequest)(nil), "pb.DeletePlayerRequest")
	proto.RegisterType((*DeletePlayerReply)(nil), "pb.DeletePlayerReply")
	proto.RegisterType((*PlayerTransferRequest)(nil), "pb.PlayerTransferRequest")
	proto.RegisterType((*PlayerTransferReply)(nil), "pb.PlayerTransferReply")
}

func init() { proto.RegisterFile("premierleague.proto", fileDescriptor_4204cc63886395c8) }

var fileDescriptor_4204cc63886395c8 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdf, 0x4e, 0x13, 0x4f,
	0x14, 0x66, 0x5b, 0x5a, 0xd8, 0xd3, 0x96, 0xc2, 0xf4, 0xc7, 0x8f, 0xb1, 0x31, 0xd8, 0x6c, 0xb8,
	0xc0, 0x44, 0x31, 0x29, 0x31, 0xc6, 0x0b, 0x03, 0x84, 0x06, 0x6e, 0x88, 0x21, 0x0b, 0x89, 0xf1,
	0x72, 0x5a, 0x0f, 0x64, 0xe3, 0x76, 0x77, 0x9c, 0x19, 0x34, 0x7d, 0x0e, 0x9f, 0xc0, 0x87, 0xf0,
	0x0d, 0x7c, 0x30, 0x33, 0xff, 0xf6, 0x0f, 0x34, 0x06, 0xe3, 0xdd, 0x7c, 0xdf, 0xf9, 0xf3, 0x1d,
	0xce, 0x77, 0xba, 0xc0, 0x80, 0x0b, 0x9c, 0x27, 0x28, 0x52, 0x64, 0xb7, 0x77, 0x78, 0xc0, 0x45,
	0xae, 0x72, 0xd2, 0xe0, 0xd3, 0xe8, 0x05, 0x74, 0xaf, 0xd9, 0x34, 0xc5, 0x18, 0xbf, 0xdc, 0xa1,
	0x54, 0xe4, 0x29, 0x84, 0x4a, 0xe3, 0xf7, 0x6c, 0x8e, 0x34, 0x18, 0x05, 0xfb, 0x61, 0x5c, 0x12,
	0xd1, 0x8f, 0x06, 0xb4, 0x4c, 0x3a, 0x19, 0xc2, 0xba, 0x42, 0x36, 0xaf, 0xa4, 0x15, 0x98, 0xec,
	0x02, 0xe8, 0xf7, 0x65, 0xca, 0x16, 0xf8, 0x89, 0x36, 0x46, 0xc1, 0x7e, 0x2b, 0xae, 0x30, 0x84,
	0xc2, 0x9a, 0x46, 0x1f, 0xf2, 0x8c, 0x36, 0x4d, 0xd0, 0x43, 0xa3, 0x8e, 0x6c, 0x3e, 0x11, 0xec,
	0x5b, 0x46, 0x57, 0x4d, 0xac, 0x24, 0xbc, 0xe6, 0x45, 0x2e, 0x15, 0x6d, 0x99, 0x60, 0x81, 0xc9,
	0xff, 0xd0, 0xd6, 0xef, 0xf3, 0x33, 0xda, 0x36, 0x11, 0x87, 0x0a, 0xfe, 0x84, 0xae, 0x55, 0xf8,
	0x93, 0x82, 0x9f, 0xd0, 0xf5, 0x0a, 0x3f, 0x29, 0x66, 0xcf, 0x93, 0x4c, 0x49, 0x1a, 0x56, 0x66,
	0x37, 0x0c, 0x19, 0x41, 0x47, 0xa3, 0x53, 0xc6, 0x13, 0xc5, 0x52, 0x0a, 0x26, 0xa1, 0x4a, 0x45,
	0x47, 0x00, 0x6e, 0xa3, 0x3c, 0x5d, 0x90, 0x67, 0xd0, 0xd2, 0x41, 0x49, 0x83, 0x51, 0x73, 0xbf,
	0x33, 0x0e, 0x0f, 0xf8, 0xf4, 0xc0, 0x86, 0x2d, 0x4f, 0x36, 0xa1, 0x89, 0x42, 0x98, 0x2d, 0x85,
	0xb1, 0x7e, 0x46, 0xcf, 0xa1, 0x73, 0x8d, 0x6c, 0xee, 0x1d, 0xf9, 0xc3, 0xa6, 0xa3, 0x5f, 0x0d,
	0x68, 0x9b, 0xa5, 0x0a, 0x42, 0x60, 0x35, 0x2b, 0x53, 0xcc, 0x5b, 0x73, 0x3a, 0xd5, 0x35, 0x37,
	0x6f, 0xfd, 0x07, 0x64, 0x4c, 0x25, 0x79, 0xc6, 0xd2, 0x44, 0x2d, 0x8c, 0x01, 0x61, 0x5c, 0xa5,
	0xb4, 0x20, 0xcf, 0x65, 0xa2, 0x09, 0xe3, 0x41, 0x18, 0x17, 0x58, 0x57, 0x33, 0xce, 0x91, 0x09,
	0xcc, 0x66, 0x28, 0x9d, 0x0b, 0x55, 0x8a, 0xfc, 0x07, 0xad, 0xdb, 0x9c, 0xa5, 0xd2, 0xf9, 0x60,
	0x81, 0xb6, 0x9c, 0x49, 0x99, 0x48, 0x25, 0x9d, 0x0f, 0x1e, 0x6a, 0x23, 0x38, 0x93, 0x12, 0xa5,
	0x37, 0xc2, 0x22, 0xb2, 0x07, 0xbd, 0x24, 0x53, 0x28, 0x66, 0xc8, 0xb5, 0xb2, 0xf7, 0xa2, 0x4e,
	0x9a, 0x53, 0x62, 0xb3, 0xcf, 0x29, 0x4a, 0x67, 0x85, 0x87, 0x7a, 0x8e, 0x9b, 0xfc, 0x2e, 0x95,
	0xb4, 0x63, 0xe7, 0x30, 0x40, 0xb3, 0x5c, 0x24, 0x33, 0xa4, 0x5d, 0xcb, 0x1a, 0x10, 0x9d, 0x42,
	0x68, 0x37, 0xae, 0x1d, 0xdb, 0x83, 0x35, 0x6e, 0x56, 0xea, 0x3d, 0x03, 0xed, 0x99, 0xdd, 0x72,
	0xec, 0x43, 0x4b, 0x6c, 0x7b, 0x09, 0xfd, 0x4b, 0xb7, 0xa6, 0x8a, 0x75, 0xc5, 0x26, 0x83, 0xfa,
	0x26, 0xa3, 0x73, 0xe8, 0x95, 0xe9, 0xff, 0xa2, 0xfb, 0x1a, 0x06, 0xa7, 0x02, 0x99, 0x42, 0x97,
	0xea, 0xb4, 0x77, 0x2b, 0xf7, 0x50, 0xef, 0x65, 0xf8, 0xe8, 0x0d, 0x6c, 0xd5, 0xcb, 0xf4, 0x0c,
	0x9b, 0xd0, 0xcc, 0xb9, 0x74, 0xb3, 0xea, 0xe7, 0x12, 0xbd, 0x77, 0x30, 0x98, 0x60, 0x8a, 0xf7,
	0xf5, 0x1e, 0x79, 0x7f, 0x5a, 0xb7, 0x5e, 0xfe, 0x58, 0xdd, 0x23, 0xd8, 0xb6, 0x25, 0xd7, 0x82,
	0x65, 0xf2, 0xe6, 0xef, 0x95, 0xdf, 0xc2, 0xe0, 0x7e, 0x83, 0x47, 0x6a, 0x8f, 0x7f, 0x06, 0xd0,
	0xbd, 0x52, 0x4c, 0xc9, 0x2b, 0x14, 0x5f, 0x93, 0x19, 0x92, 0x57, 0x10, 0x5e, 0x24, 0x52, 0xd9,
	0x6f, 0xe1, 0x66, 0xf9, 0xa3, 0xb6, 0x23, 0x0d, 0x37, 0x2a, 0x0c, 0x4f, 0x17, 0xd1, 0x0a, 0x39,
	0x84, 0xbe, 0x29, 0xf0, 0x5f, 0x41, 0x21, 0x49, 0xdf, 0x24, 0x95, 0xbf, 0xf4, 0x61, 0xaf, 0x24,
	0x6c, 0xd1, 0x11, 0x0c, 0x74, 0x91, 0xbf, 0x13, 0x5f, 0x38, 0x30, 0x66, 0xd6, 0x6f, 0x6d, 0xb8,
	0x55, 0x27, 0x4d, 0x83, 0xf1, 0xf7, 0x00, 0x7a, 0xb6, 0xca, 0x0f, 0x7e, 0x0c, 0xdd, 0xaa, 0xed,
	0x64, 0x47, 0x97, 0x2d, 0xb9, 0x9f, 0xe1, 0xf6, 0xc3, 0x80, 0x1d, 0xea, 0x18, 0xba, 0xce, 0xc0,
	0x8b, 0xb2, 0xc3, 0x92, 0x8b, 0xb0, 0x1d, 0x1e, 0x78, 0x1d, 0xad, 0x8c, 0x3f, 0x42, 0xdf, 0x5b,
	0xe0, 0xc7, 0x3a, 0x83, 0x0d, 0x4f, 0xb9, 0xc1, 0x9e, 0x94, 0x17, 0x7b, 0xcf, 0xf0, 0xe1, 0xce,
	0xb2, 0x90, 0x69, 0x3d, 0x6d, 0x9b, 0xff, 0x6c, 0x87, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcc,
	0xfd, 0x20, 0xf2, 0xf0, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatsServiceClient interface {
	ListTable(ctx context.Context, in *TableRequest, opts ...grpc.CallOption) (*TableReply, error)
	ListTeamPlayers(ctx context.Context, in *TeamRequest, opts ...grpc.CallOption) (*TeamReply, error)
	ListPositionPlayers(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (*PositionReply, error)
}

type statsServiceClient struct {
	cc *grpc.ClientConn
}

func NewStatsServiceClient(cc *grpc.ClientConn) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) ListTable(ctx context.Context, in *TableRequest, opts ...grpc.CallOption) (*TableReply, error) {
	out := new(TableReply)
	err := c.cc.Invoke(ctx, "/pb.StatsService/ListTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) ListTeamPlayers(ctx context.Context, in *TeamRequest, opts ...grpc.CallOption) (*TeamReply, error) {
	out := new(TeamReply)
	err := c.cc.Invoke(ctx, "/pb.StatsService/ListTeamPlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) ListPositionPlayers(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (*PositionReply, error) {
	out := new(PositionReply)
	err := c.cc.Invoke(ctx, "/pb.StatsService/ListPositionPlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
type StatsServiceServer interface {
	ListTable(context.Context, *TableRequest) (*TableReply, error)
	ListTeamPlayers(context.Context, *TeamRequest) (*TeamReply, error)
	ListPositionPlayers(context.Context, *PositionRequest) (*PositionReply, error)
}

// UnimplementedStatsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStatsServiceServer struct {
}

func (*UnimplementedStatsServiceServer) ListTable(ctx context.Context, req *TableRequest) (*TableReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTable not implemented")
}
func (*UnimplementedStatsServiceServer) ListTeamPlayers(ctx context.Context, req *TeamRequest) (*TeamReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTeamPlayers not implemented")
}
func (*UnimplementedStatsServiceServer) ListPositionPlayers(ctx context.Context, req *PositionRequest) (*PositionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPositionPlayers not implemented")
}

func RegisterStatsServiceServer(s *grpc.Server, srv StatsServiceServer) {
	s.RegisterService(&_StatsService_serviceDesc, srv)
}

func _StatsService_ListTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).ListTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StatsService/ListTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).ListTable(ctx, req.(*TableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_ListTeamPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).ListTeamPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StatsService/ListTeamPlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).ListTeamPlayers(ctx, req.(*TeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_ListPositionPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).ListPositionPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StatsService/ListPositionPlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).ListPositionPlayers(ctx, req.(*PositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTable",
			Handler:    _StatsService_ListTable_Handler,
		},
		{
			MethodName: "ListTeamPlayers",
			Handler:    _StatsService_ListTeamPlayers_Handler,
		},
		{
			MethodName: "ListPositionPlayers",
			Handler:    _StatsService_ListPositionPlayers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "premierleague.proto",
}

// PlayerServiceClient is the client API for PlayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerServiceClient interface {
	CreatePlayer(ctx context.Context, in *CreatePlayerRequest, opts ...grpc.CallOption) (*CreatePlayerReply, error)
	DeletePLayer(ctx context.Context, in *DeletePlayerRequest, opts ...grpc.CallOption) (*DeletePlayerReply, error)
}

type playerServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlayerServiceClient(cc *grpc.ClientConn) PlayerServiceClient {
	return &playerServiceClient{cc}
}

func (c *playerServiceClient) CreatePlayer(ctx context.Context, in *CreatePlayerRequest, opts ...grpc.CallOption) (*CreatePlayerReply, error) {
	out := new(CreatePlayerReply)
	err := c.cc.Invoke(ctx, "/pb.PlayerService/CreatePlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) DeletePLayer(ctx context.Context, in *DeletePlayerRequest, opts ...grpc.CallOption) (*DeletePlayerReply, error) {
	out := new(DeletePlayerReply)
	err := c.cc.Invoke(ctx, "/pb.PlayerService/DeletePLayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServiceServer is the server API for PlayerService service.
type PlayerServiceServer interface {
	CreatePlayer(context.Context, *CreatePlayerRequest) (*CreatePlayerReply, error)
	DeletePLayer(context.Context, *DeletePlayerRequest) (*DeletePlayerReply, error)
}

// UnimplementedPlayerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerServiceServer struct {
}

func (*UnimplementedPlayerServiceServer) CreatePlayer(ctx context.Context, req *CreatePlayerRequest) (*CreatePlayerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlayer not implemented")
}
func (*UnimplementedPlayerServiceServer) DeletePLayer(ctx context.Context, req *DeletePlayerRequest) (*DeletePlayerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePLayer not implemented")
}

func RegisterPlayerServiceServer(s *grpc.Server, srv PlayerServiceServer) {
	s.RegisterService(&_PlayerService_serviceDesc, srv)
}

func _PlayerService_CreatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).CreatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PlayerService/CreatePlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).CreatePlayer(ctx, req.(*CreatePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_DeletePLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).DeletePLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PlayerService/DeletePLayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).DeletePLayer(ctx, req.(*DeletePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlayerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PlayerService",
	HandlerType: (*PlayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlayer",
			Handler:    _PlayerService_CreatePlayer_Handler,
		},
		{
			MethodName: "DeletePLayer",
			Handler:    _PlayerService_DeletePLayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "premierleague.proto",
}

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransferServiceClient interface {
	TransferPlayer(ctx context.Context, in *PlayerTransferRequest, opts ...grpc.CallOption) (*PlayerTransferReply, error)
}

type transferServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransferServiceClient(cc *grpc.ClientConn) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) TransferPlayer(ctx context.Context, in *PlayerTransferRequest, opts ...grpc.CallOption) (*PlayerTransferReply, error) {
	out := new(PlayerTransferReply)
	err := c.cc.Invoke(ctx, "/pb.TransferService/TransferPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferServiceServer is the server API for TransferService service.
type TransferServiceServer interface {
	TransferPlayer(context.Context, *PlayerTransferRequest) (*PlayerTransferReply, error)
}

// UnimplementedTransferServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransferServiceServer struct {
}

func (*UnimplementedTransferServiceServer) TransferPlayer(ctx context.Context, req *PlayerTransferRequest) (*PlayerTransferReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferPlayer not implemented")
}

func RegisterTransferServiceServer(s *grpc.Server, srv TransferServiceServer) {
	s.RegisterService(&_TransferService_serviceDesc, srv)
}

func _TransferService_TransferPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).TransferPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TransferService/TransferPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).TransferPlayer(ctx, req.(*PlayerTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransferService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferPlayer",
			Handler:    _TransferService_TransferPlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "premierleague.proto",
}
